#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: my-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: manual
#  hostPath:
#    path: /mnt/data
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: my-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 500Mi
#  storageClassName: manual
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: bXlzcWxfcGFzc3dvcmQ=   # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
#        volumeMounts:
#        - name: mysql-storage
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: mysql-storage
#        persistentVolumeClaim:
#          claimName: my-pvc
