apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-rb
subjects:
- kind: ServiceAccount
  name: node-sa
roleRef:
  kind: Role
  name: node-role
  apiGroup: rbac.authorization.k8s.io